### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by snow-abstraction** [GBDT-PL/GBDT-PL#5]
This is an interesting project. It would be useful if a license (LICENSE file) was added to clarify the permitted use of this code. This would encourage people to understand and appreciate this good work.

Since this is partially funded by Microsoft maybe you could use the same license as LightGBM:
https://github.com/microsoft/LightGBM/blob/master/LICENSE

Thank you.

**Comment by shiyu1994** [comment]
Done via [80c3da5](https://github.com/GBDT-PL/GBDT-PL/commit/80c3da58fd2a7861a033251fcebe68ad3193ab9b). Thanks for the reminder!
